### ISSUE TITLE
游玩原神会出现大核不工作的情况

### ISSUE THREAD

**Issue by iisnsb** [FlowerWorks/Apodidae#26]
### Bug 描述

通过scene的帧率记录发现游玩原神会出现大核占用率和频率异常，占用率为0，频率为800mhz

### 复现步骤

使用天玑1200的配置文件游玩原神即可

### 预期行为

增加支持设备

### 屏幕捕获

[原神 2024-06-22 10-41-15 .csv](https://github.com/user-attachments/files/15935789/2024-06-22.10-41-15.csv)

### 版本信息

Android 11
Apodidae v4.0.13

**Comment by naranyinyun** [comment]
这个文件是？

**Comment by iisnsb** [comment]
@naranyinyun scene的帧率记录文件

**Comment by iisnsb** [comment]
![Uploading Screenshot_2024-06-22-16-33-52-13.jpg…]()

**Comment by iisnsb** [comment]
![Screenshot_2024-06-22-16-33-52-13](https://github.com/FlowerWorks/Apodidae/assets/103032607/233fb466-6509-4084-a6f5-1b35e9702305)

**Comment by iisnsb** [comment]
@naranyinyun 这是scene的截图

**Comment by naranyinyun** [comment]
其他游戏也会出现这种情况吗?

**Comment by iisnsb** [comment]
@naranyinyun 其它游戏不会出现

**Comment by XiaHuaBeiChiDiaoLe** [comment]
我们会在空闲时间尝试解决此问题 如果原神游戏时间占据您手机使用时间的大多数 请尝试回退上一版本的配置文件以及Cutoolbox 如果只是测试或者休闲时间短暂游戏 可酌情考虑自行选择版本

**Comment by XiaHuaBeiChiDiaoLe** [comment]
并且游玩游戏时可以使用均衡-性能-极速 逐步切换模式 极速模式不一定在游戏时有最佳表现 反而可能会造成卡顿或者功耗异常

**Comment by iisnsb** [comment]
@XiaHuaBeiChiDiaoLe  谢谢，我会尝试切换模式的

**Comment by naranyinyun** [comment]
[dimensity1100.json](https://github.com/user-attachments/files/15936734/dimensity1100.json)

目前看来可能是调度问题，这个配置文件修改了超大核的基础频率并调整了 Performance 模式下 Swipe 的 Boost  

但另一方面，也极为可能是米哈游的优化问题  
![Screenshot_2024-06-22-21-37-57-152_cu monitor](https://github.com/FlowerWorks/Apodidae/assets/91950505/8dd28dae-f819-4a71-81f6-36be6b8839c9)
这是联发科 天玑 8100 的 CPU 频率图，在没有使用调度的情况下 Cluster 3 的频率也并不高

**Comment by iisnsb** [comment]
@naranyinyun  应该不是米哈游优化问题，我之前游玩时大核占用率是正常的

**Comment by naranyinyun** [comment]
> @naranyinyun 应该不是米哈游优化问题，我之前游玩时大核占用率是正常的

可以试一下那个配置文件

**Comment by iisnsb** [comment]
@naranyinyun 您发的那个？

**Comment by iisnsb** [comment]
@naranyinyun 占用率基本为0，基础频率的确上升了

**Comment by iisnsb** [comment]
@naranyinyun 我发现超大核会在进入门之前加载一个圆圈(可能是账户登录?)的时候，占用率和频率会上升

**Comment by naranyinyun** [comment]
> @naranyinyun 我发现超大核会在进入门之前加载一个圆圈(可能是账户登录?)的时候，占用率和频率会上升

让虾滑处理吧，1200 的维护者不是我

**Comment by TachibanaAoi** [comment]
目前认为可能是Cutoolbox的问题，perfMargin(Cluster 3)已经给到了30。至于加载时大核频率有所.上升的情况，可能触发了bigjank加速。如果把boost给到40会导致功耗超过4W。

Cutoolbox还无法在天玑 8100 上正常工作,所以没有可供的同架构参考。如果Cutoolbox版本更新,我会尝试修复。您可以尝试Cutoolbox官调或者其他作者的配置文件。如果奏效,烦请将奏效的文件提供给我们，有助于Apodidae修复问题。

如果需要，您可以在排除后在 Cutoolbox 提出 Issue，或者尝试旧版的 Cutoolbox 搭配旧版的 Apodidae。

感谢理解

**Comment by iisnsb** [comment]
非常感谢，更新Cutoolbox后大核就正常工作了
________________________________
发件人: 立华青 ***@***.***>
发送时间: 2024年6月30日 12:28
收件人: FlowerWorks/Apodidae ***@***.***>
抄送: iisnsb ***@***.***>; Author ***@***.***>
主题: Re: [FlowerWorks/Apodidae] 游玩原神会出现大核不工作的情况 (Issue #26)


目前认为可能是Cutoolbox的问题，perfMargin(Cluster 3)已经给到了30。至于加载时大核频率有所.上升的情况，可能触发了bigjank加速。如果把boost给到40会导致功耗超过4W。

Cutoolbox还无法在天玑 8100 上正常工作,所以没有可供的同架构参考。如果Cutoolbox版本更新,我会尝试修复。您可以尝试Cutoolbox官调或者其他作者的配置文件。如果奏效,烦请将奏效的文件提供给我们，有助于Apodidae修复问题。

如果需要，您可以在排除后在 Cutoolbox 提出 Issue，或者尝试旧版的 Cutoolbox 搭配旧版的 Apodidae。

感谢理解

―
